name: Macports
on: [push]
jobs:
  macOS:
    name: Run macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Command line
        run: |
          id
          echo $PATH
          brew list --versions
      - name: Python
        run: |
          which python2.7
          ls -l $(which python 2.7)
          python2.7 --version
          which python3
          ls -l $(which python3)
          python3 --version
          which python3.7
          ls -l $(which python3.7)
          python3.7 --version
      - name: Default Xcode
        run: |
          xcode-select -p
          xcodebuild -version
      - name: Set Xcode to 10.3
        run: |
          sudo xcode-select -s /Applications/Xcode_10.3.app/Contents/Developer
          xcodebuild -version
      - name: Download Macports
        run: |
          curl -vsO https://distfiles.macports.org/MacPorts/MacPorts-2.5.4-10.14-Mojave.pkg
      - name: Install Macports
        run: |
          sudo /usr/sbin/installer -verbose -pkg MacPorts-2.5.4-10.14-Mojave.pkg -target /
          sudo ln -s $(which cmake) /opt/local/bin/cmake
      - name: Install first Macport double-conversion using Cmake
        run: |
          /opt/local/bin/port version
          /opt/local/bin/cmake --version
          sudo /opt/local/bin/port -vs install double-conversion
