name: Macports
on: [push]
jobs:
  macOS:
    name: Run macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Echo $PATH an id
        run: |
          echo $PATH
          id
      - name: Check for command line tools
        run: |
          brew list --versions
          which xz &&  xz --version
          which cmake && cmake --version
          which pkgconfig && pkgconfig --version
          which gawk && gawk --version
          which autoconf && autoconf --version
          which automake && automake --version
      - name: Default python 2
        run: |
          which python2.7
          ls -l $(which python 2.7)
          python2.7 --version
      - name: Default python 3
        run: |
          which python3
          ls -l $(which python3)
          python3 --version
      - name: Default python 3.7
        run: |
          which python3.7
          ls -l $(which python3.7)
          python3.7 --version
      - name: Default Xcode
        run: |
          xcode-select -p
          xcodebuild -version
      - name: Set Xcode to 10.3
        run: |
          sudo xcode-select -s /Applications/Xcode_10.3.app/Contents/Developer
          xcodebuild -version
      - name: Download Macports
        run: |
          curl -vsO https://distfiles.macports.org/MacPorts/MacPorts-2.5.4-10.14-Mojave.pkg
      - name: Install Macports
        run: |
          sudo /usr/sbin/installer -verbose -pkg MacPorts-2.5.4-10.14-Mojave.pkg -target /
          sudo ln -s $(which cmake) /opt/local/bin/cmake
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
      - name: Macports version and info qt5
        run: |
          port version
          port info qt5
          /opt/local/bin/cmake --version
