name: Macports
on: [push]
jobs:
  macOS:
    name: Run macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Echo $PATH an id
        run: |
          echo $PATH
          id
      - name: Default xz path and version
        run: |
          which xz
          xz --version
          - name: Default cmake path and version
        run: |
          which cmake
          cmake --version
      - name: Default python 2
        run: |
          which python2.7
          ls -l $(which python 2.7)
          python2.7 --version
      - name: Default python 3
        run: |
          which python3
          ls -l $(which python3)
          python3 --version
      - name: Default python 3.7
        run: |
          which python3.7
          ls -l $(which python3.7)
          python3.7 --version
      - name: Default Xcode path
        run: |
          xcode-select -p
      - name: Default Xcode version
        run: |
          xcodebuild -version
      - name: Set Xcode to 10.3
        run: |
          sudo xcode-select -s /Applications/Xcode_10.3.app/Contents/Developer
      - name: Xcode version
        run: |
          xcodebuild -version
      - name: Download Macports
        run: |
          curl -vsO https://distfiles.macports.org/MacPorts/MacPorts-2.5.4-10.14-Mojave.pkg
      - name: Install Macports
        run: |
          sudo /usr/sbin/installer -verbose -pkg MacPorts-2.5.4-10.14-Mojave.pkg -target /
          ln -s $(which cmake) /opt/local/bin/cmake
      - name: Macports version and info qt5
        run: |
          /opt/local/bin/port version
          /opt/local/bin/port info qt5
          /opt/local/bin/cmake --version
