name: Macports
on: [push]
jobs:
  macOS:
    name: Run macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Echo $PATH an id
        run: |
          echo $PATH
          id
      - name: Default Xcode path
        run: |
          xcode-select -p
      - name: Default Xcode version
        run: |
          xcodebuild -version
      - name: Set Xcode to 10.3
        run: |
          sudo xcode-select -s /Applications/Xcode_10.3.app/Contents/Developer
      - name: Xcode version
        run: |
          xcodebuild -version
      - name: Download Macports
        run: |
          curl -vsO https://distfiles.macports.org/MacPorts/MacPorts-2.5.4-10.14-Mojave.pkg
      - name: Install Macports
        run: |
          sudo /usr/sbin/installer -verbose -pkg MacPorts-2.5.4-10.14-Mojave.pkg -target /