name: Macports
on: [push]
jobs:
  macOS:
    name: Run macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Command line
        run: |
          id
          echo $PATH
          brew list --versions
      - name: Python
        run: |
          which python2.7
          ls -l $(which python 2.7)
          python2.7 --version
          which python3
          ls -l $(which python3)
          python3 --version
          which python3.7
          ls -l $(which python3.7)
          python3.7 --version
      - name: Default Xcode
        run: |
          xcode-select -p
          xcodebuild -version
      - name: Set Xcode to 10.3
        run: |
          sudo xcode-select -s /Applications/Xcode_10.3.app/Contents/Developer
          xcodebuild -version
      - name: MacPorts
        uses: WildbookOrg/actions/setup-macports@v1.0.0
      - name: Install first Macport double-conversion using Cmake
        run: |
          port version
          ls -l $(which cmake)
          cmake --version
          sudo port -vs install double-conversion
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with: 
          name: double-conversion
          path: /opt/local/var/macports/software/double-conversion