name: Macports
on: [push]
jobs:
  macOS:
    name: Run macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Echo $PATH an id
        run: |
          echo $PATH
          id
      - name: Default Xcode path
        run: |
          echo Default Xcode path \`xcode-select -p\`
          xcode-select -p
      - name: Default Xcode version
        run: |
          echo Default Xcode version \`xcodebuild -version\`
          xcodebuild -version
      - name: Download Macports
        run: |
          echo Download Macports
          curl -vsO https://distfiles.macports.org/MacPorts/MacPorts-2.5.4-10.14-Mojave.pkg
      - name: Install Macports
        run: |
          echo Install Macports
          /usr/sbin/installer -verbose -pkg MacPorts-2.5.4-10.14-Mojave.pkg -target /